<?php

namespace AppBundle\Repository\Work;

use Doctrine\ORM\EntityRepository;

/**
 * ProblemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProblemeRepository extends EntityRepository
{
}
