<?php

namespace AppBundle\Repository\Security;

use Doctrine\ORM\EntityRepository;

/**
 * TechnicienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnicienRepository extends EntityRepository
{
}
